id: PE88627C7
initial_creation_type: input
source_metadata:
  title: Dharma Protectors Series
  language: pt
  description: 'The following texts are now available as part of our Dharma Protectors
    (dharmapāla; Tib. chos skyong) series:'
  volume:
    f135608a95f44c5398944a498d4dbb41:
      title: Brief Dharmapālas Offering
      parent: General
    09a6a77ff3fd43c084cfcaa09f797a9b:
      title: Brief Protectors Practice
      parent: General
    ee450a0ce27a44f4888a54495e8ee7e2:
      title: Expeditious Activity Torma Offering
      parent: General
    48c396d3ccdb4c798d6681c840b4f0eb:
      title: Wayfaring Offering
      parent: General
    3d293be494ce477f9fa31031ccad0900:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: General
    ae5805915c5d45439e91bd17675b9eb3:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: General
    362bc1d46c5842aa9074de79d7b1927c:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Changshönma
    53ef09e2743f4538af8ee49eca71d428:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Durtrö Lhamo
    03aff3b21e7349e3bbc6471185fd49de:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Eight Classes
    34bf73e73fdf4f65a30c467fc45e77b7:
      title: Restorative Offering to the Eight Classes
      parent: Eight Classes
    8e3afe26f0684f798d4c40344eeeb2b2:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Ekajaṭī
    c4acd9b6431d4bccbaa9e8ff2e9d8c16:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Five Medicine Sisters
    a6f563b582564023b96c71822cb42fa4:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Gesar
    b0b3492ec71f4c3d8c96706320ecd00b:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    9c5eddf9d76e4378b6e7e7655d4b2fb0:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    dc0f21f319e64b9cb4a96f35e19bdabb:
      title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer
        to Mahākāla and Consort'
      parent: Mahākāla
    e7e1cc2769ad4c739548ab607b755d12:
      title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to
        the Glorious Guru Mahākāla Pañjaranātha'
      parent: Mahākāla
    06b0a9e40fe645a18a7f82c9870fabf3:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
    19a24cdcffa14e18927a9d19b41b6459:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Pacifying the Turmoil of the Mamos
    4ca69183edf64aeebae1e2d3064f21f1:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Pacifying the Turmoil of the Mamos
    5dadf9a2291e42089ba34ac3e919b8dd:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Pukkasī
    4350292fe56446efa8257ed11870ae3a:
      title: Brief Offering Prayer to Za Rāhula
      parent: Rāhula
    7a5c3c509ffb4c38a5bb0063e7cd8a2a:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Serkyem
    462b5a54ef634636b2b2b53b64b4bd37:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Tsiu Marpo
    f375d3b66b124dfaa7f785320c9a5d4f:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Vajrasādhu
    4ce8b70d592b494d8971e5fe372e4419:
      title: Yarlha Shampo Sang Offering
      parent: Yarlha Shampo
created_at: '2022-03-01T03:27:20.283853'
last_modified_at: '2022-03-01T03:27:20.283856'
